### ISSUE TITLE
Keep getting exception when creating new assembler

### ISSUE THREAD

**Issue by bobhang** [Reloaded-Project/Reloaded.Assembler#1]
Var asm = new Assembler();

Keeps throwing the following error:

System.ArgumentNullException: Value cannot be null parameter name: ptr 

I installed from the NuGet Package. Do you have any ideas what would cause this?

**Comment by Sewer56** [comment]
Is it possible that you are using an outdated package version?
It may also be possible that I have packed it wrong.

I just tried 1.0.5 (published around an hour ago) in an empty x64 .NET Core project and it does seem to work correctly.

![image](https://user-images.githubusercontent.com/6697380/56835848-47fd0900-686d-11e9-885d-a20f85b8cd6d.png)

**Comment by Sewer56** [comment]
Okay I checked on another machine and on .NET Framework in addition as opposed to .NET Core.
No changes, the package seems to work fine for me.

![image](https://user-images.githubusercontent.com/6697380/56836302-bb534a80-686e-11e9-9592-527022fb4a1f.png)

PS. Also make sure to use `Reloaded.Assembler` on NuGet. 
**Don't use Reloaded-Assembler**. That is a relic from [Reloaded-Mod-Loader](https://github.com/Sewer56/Reloaded-Mod-Loader) which currently being refactored + rewritten in smaller, tested, more managable chunks over here in Reloaded-Project.

The name similarity does annoy me, but until Reloaded-Mod-Loader is obsolete I have to keep that old package up.

**Comment by Sewer56** [comment]
Closed due inactivity.
