### ISSUE TITLE
Conflict with Reloaded.Memory.Sigscan

### ISSUE THREAD

**Issue by coolzoom** [Reloaded-Project/Reloaded.Assembler#4]
If i use Sigcan together with Assembler, the sigscan would throw error like below

```
            Scanner Scans = new Scanner(Client.Proc, Client.Proc.MainModule);
            var scanResult = Scans.FindPattern_Compiled(pattern).Offset;


System.TypeLoadException:“Method 'FindPattern_Avx2' in type 'Reloaded.Memory.Sigscan.Scanner' from assembly 'Reloaded.Memory.Sigscan, Version=3.1.4.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.”
```

**Comment by Sewer56** [comment]
I'm currently out, but I'd imagine it would just be because one of your projects targets newer sigscan while another references another version.

Poke around your dependencies for now.

**Comment by coolzoom** [comment]
> I'm currently out, but I'd imagine it would just be because one of your projects targets newer sigscan while another references another version with breaking API change.
> 
> Poke around your dependencies for now.

Alright, no hurry

**Comment by Sewer56** [comment]
This is a dependency version conflict between two NuGet packages you have , but Assembler is not one of them as it doesn't depend on SigScan. It's probably some two other dependencies.

You'll need to look through the dependencies that reference sigscan (transitively or directly). Not sure if there's a tool for that out there.

**Comment by coolzoom** [comment]
Thanks! I pulled the Reloaded.Assembler source instead of using the NuGet package, and tweaking around,  

changed from
```
    <PackageReference Include="Reloaded.Memory.Buffers" Version="2.0.0" />
    <PackageReference Include="Reloaded.Memory.Sigscan" Version="3.1.4" />
```
to
```
    <PackageReference Include="Reloaded.Memory.Buffers" Version="1.4.6" />
    <PackageReference Include="Reloaded.Memory.Sigscan" Version="1.2.1" />
```
now they work together just fine.
Cheers!

**Comment by Sewer56** [comment]
I didn't get around to commenting here but I actually fixed the problem yesterday, turns out there was a feature mismatch in terms of what was built for net5.0 between SigScan and Definitions library. Using the latest SigScan library would also resolve the issue.

**Comment by coolzoom** [comment]
Thanks Man!
